version: '3.9'
services:
  daniel:
    image: miapp
    build: .
    ports:
      - "4000:4000"
    links:
      - mi-mysql
  mi-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345